export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS'
export const SET_ONE_PRODUCT = 'SET_ONE_PRODUCT'
export const SET_ALL_CATEGORIES = ' SET_ALL_CATEGORIES'
export const SET_ONE_CATEGORY = 'SET_ONE_CATEGORY'
export const SET_ALL_SUPPLIERS = 'SET_ALL_SUPPLIERS'
export const SET_ONE_SUPPLIER = 'SET_ONE_SUPPLIER'
export const SET_MESSAGE_ADD_PRODUCT = 'SET_MESSAGE_ADD_PRODUCT'

